request to merge assignment 1 into develop branch
munendra-successive/React-training pull request #1
Opened 2023-10-26 10:52 UTC by munendra-successive

1.Create a functional component named Greeting that displays a simple "Hello, React!" message on the screen.
Import and render the Greeting component in the App component.

2.Create a functional component named UserCard that accepts the following props: name, email, and avatarURL.
Use the props to display the user's name, email, and an image (avatar) in the UserCard component.
Create multiple instances of the UserCard component with different user data.

3.Create a functional component named Weather that accepts a prop called temperature (a number).
Display a message like "It's sunny today!" if the temperature is above 25°C and "It's cold today!" if the temperature is below 10°C.
Import and render the Weather component in the App component with different temperature values.

4.Create a functional component named Counter that displays a count and two buttons: "Increment" and "Decrement".
Implement event handlers for the "Increment" and "Decrement" buttons to increase and decrease the count.
Display the updated count on the screen.

5.Create a functional component named TaskList that accepts an array of task names as a prop.
Use the map function to render each task name as a list item.
Import and render the TaskList component in the App component with an array of tasks.

6.Create a functional component named Button that accepts props for text and color.
Style the button using inline styles or CSS classes based on the color prop.
Import and render the Button component in the App component with different text and color props.

2023-10-26 12:00 UTC, UrvashiChaudhary requested changes

2023-10-26 12:00 UTC, UrvashiChaudhary commented on assignment-1/package.json
> +{
package.json, public directory, node_modules, gitignore, package-lock.json should be in parent directory, not in assignment1

2023-10-26 12:00 UTC, UrvashiChaudhary commented on assignment-1/.gitignore
> +
add package-lock.json in .gitignore

2023-10-26 12:00 UTC, UrvashiChaudhary commented on assignment-1/public/robots.txt
> +# https://www.robotstxt.org/robotstxt.html
Delete this file if not required

2023-10-26 12:00 UTC, UrvashiChaudhary commented on assignment-1/src/App.css
> +}
Remove this file if not required

2023-10-26 12:00 UTC, UrvashiChaudhary commented on assignment-1/src/logo.svg
Please remove it if you're not using it.

2023-10-30 09:38 UTC, munendra-successive commented on assignment-1/package.json
> +{
Changed the directory of package.json, public directory, node_modules, gitignore, and package-lock.json to parent

2023-10-30 09:39 UTC, munendra-successive commented on assignment-1/.gitignore
> +
Added package-lock.json in .gitignore

2023-10-30 09:39 UTC, munendra-successive commented on assignment-1/public/robots.txt
> +# https://www.robotstxt.org/robotstxt.html
Deleted robots.txt

2023-10-30 09:39 UTC, munendra-successive commented on assignment-1/src/App.css
> +}
Deleted App.css

2023-10-30 09:39 UTC, munendra-successive commented on assignment-1/src/logo.svg
removed logo.svg

2023-10-30 09:40 UTC, merged